"""Brain-grounded steering: matched vs unmatched question lift (Fig 7, §8.2).

Recomputes the gap-targeted - baseline ADQA delta straight from the cross-judge
per-question CSVs so the figure is tied to disk, not hand-entered numbers.

Two cross-family-judged runs (GPT-5 grading content generated by a different model):
  - 60-clip external
  - 17-clip held-out, non-headroom-selected (clean, no baseline-low selection)

Each split into questions whose required visual evidence MATCHED the TRIBE-flagged
blind-spot type vs UNMATCHED. The claim is the dissociation: matched lifts, unmatched
does not. Bars show mean paired delta with a 95% bootstrap CI; W/L/T and Cohen's d
annotated. Solid colors only (PDF-perf rule in CLAUDE.md).
"""
from __future__ import annotations

import csv
import os
from collections import defaultdict

import matplotlib.pyplot as plt
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "..", "cursor", "research", "output")
OUT = os.path.join(HERE, "scenetwin_steering_matched.png")

RUNS = [
    ("GPT-5 judge\n60 clips", "tribe_crossjudge_gpt5_perq.csv"),
    ("GPT-5 judge\n17 clips (non-headroom)", "tribe_crossjudge_opus_17_perq.csv"),
]


def load_pairs(path):
    """Return paired (baseline, gap_targeted) deltas keyed by matched flag."""
    by_key = defaultdict(dict)
    matched_of = {}
    with open(path) as fh:
        for r in csv.DictReader(fh):
            key = (r["video_id"], r["q_idx"])
            by_key[key][r["condition"]] = float(r["score"])
            matched_of[key] = int(r["matched"])
    diffs = {0: [], 1: []}
    for key, conds in by_key.items():
        if "baseline" in conds and "gap_targeted" in conds:
            diffs[matched_of[key]].append(conds["gap_targeted"] - conds["baseline"])
    return diffs


def stats(d):
    a = np.asarray(d, dtype=float)
    n = len(a)
    mean = a.mean()
    sd = a.std(ddof=0)
    cohen_d = mean / sd if sd > 0 else 0.0
    w = int((a > 0).sum()); l = int((a < 0).sum()); t = int((a == 0).sum())
    # 95% bootstrap CI on the mean paired delta
    rng = np.random.default_rng(0)
    boot = np.array([rng.choice(a, size=n, replace=True).mean() for _ in range(5000)])
    lo, hi = np.percentile(boot, [2.5, 97.5])
    return dict(n=n, mean=mean, d=cohen_d, w=w, l=l, t=t, lo=lo, hi=hi)


C_MATCH = "#2a8a40"     # green: TRIBE-flagged questions
C_UNMATCH = "#b0b3b6"   # grey: questions TRIBE did not flag

fig, ax = plt.subplots(figsize=(8.2, 5.2))

xticks, xlabels = [], []
width = 0.36
for i, (label, fname) in enumerate(RUNS):
    diffs = load_pairs(os.path.join(DATA, fname))
    sm = stats(diffs[1])  # matched
    su = stats(diffs[0])  # unmatched
    xm, xu = i - width / 2, i + width / 2
    ax.bar(xm, sm["mean"], width, color=C_MATCH,
           yerr=[[sm["mean"] - sm["lo"]], [sm["hi"] - sm["mean"]]],
           capsize=4, ecolor="#333333",
           label="matched (TRIBE-flagged)" if i == 0 else None)
    ax.bar(xu, su["mean"], width, color=C_UNMATCH,
           yerr=[[su["mean"] - su["lo"]], [su["hi"] - su["mean"]]],
           capsize=4, ecolor="#333333",
           label="unmatched" if i == 0 else None)
    # Anchor labels just above each bar top (the mean), not above the CI whisker,
    # so wide CIs (small-n matched run) do not push text off-axis.
    ax.text(xm, sm["mean"] + 0.006,
            f"+{sm['mean']:.3f}  d={sm['d']:.2f}\n{sm['w']}/{sm['l']}/{sm['t']}",
            ha="center", va="bottom", fontsize=8.5, color=C_MATCH, fontweight="bold")
    ax.text(xu, max(su["mean"], 0.0) + 0.006,
            f"+{su['mean']:.3f}  d={su['d']:.2f}\n{su['w']}/{su['l']}/{su['t']}",
            ha="center", va="bottom", fontsize=8.5, color="#666666")
    xticks.append(i); xlabels.append(label)

ax.axhline(0, color="#333333", linewidth=0.8)
ax.set_xticks(xticks)
ax.set_xticklabels(xlabels, fontsize=10)
ax.set_ylabel("mean ADQA delta  (gap-targeted - baseline)", fontsize=10)
ax.set_title("Brain-grounded steering lands on the questions TRIBE flagged\n"
             "(cross-family judge; W/L/T = wins/losses/ties; whiskers = 95% bootstrap CI)",
             fontsize=11, pad=12)
ax.set_ylim(-0.06, 0.32)
ax.legend(loc="upper left", frameon=False, fontsize=9.5)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
fig.tight_layout()
fig.savefig(OUT, dpi=150)
print("wrote", OUT)
