#!/usr/bin/env python3
"""Build a VALID 4th tier: machine-generated AD (Gemini grader, self-contained).

Replaces the fake "long VATEX" rung (wordiest crowd caption) with a genuinely
distinct quality class — an automated audio description generated by a vision LLM
from the clip frames. Expected ladder:

    tier0 cross control < tier1 crowd caption < tierM machine AD < tier3 expert AD

To keep it apples-to-apples, ALL FOUR tiers are graded blind by the SAME model
(Gemini) against the cached frame-grounded questions. CLIP is local/deterministic.

Per clip:
  1. Generate machine AD from the 8 frames (Gemini vision, pro-AD word budget).
  2. Blind-grade all 4 candidates {cross, crowd-short, machine-AD, expert} against
     the cached questions (shuffled A/B/C/D).
  3. CLIP top3: reuse cached scores for the 3 existing tiers, compute locally for
     machine AD.
  4. Within-clip minmax + 50/50 ensemble; report rho and tier ordering.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from PIL import Image
from scipy.stats import spearmanr

ROOT = Path(__file__).resolve().parents[2]
CURSOR = ROOT / "cursor"
EXT_DIR = CURSOR / "data" / "external_clips"
FRAMES_ROOT = EXT_DIR / "frames"
REGISTRY = EXT_DIR / "registry.jsonl"
QUESTIONS_CSV = CURSOR / "output" / "external_adqa" / "external_adqa_questions.csv"
CLIP_CSV = CURSOR / "output" / "external_clip_full_eval.csv"
CACHE = CURSOR / "output" / "machine_ad" / "cache"
OUT_CSV = CURSOR / "output" / "machine_ad" / "machine_ad_tier.csv"
OUT_JSON = CURSOR / "output" / "machine_ad_tier.json"
FINDINGS = CURSOR / "findings" / "machine-ad-tier.md"
CHART = ROOT / "output" / "charts" / "scenetwin_machine_ad_ladder.png"

# Grader is swappable: set via configure() / CLI. Default Gemini (only provider
# with live credits at time of writing). Swap to Opus or GPT with one flag once
# Anthropic/OpenAI credits are topped up — the rest of the pipeline is identical.
PROVIDER = "gemini"
MODEL = "gemini-2.5-flash"
DEFAULT_MODEL = {
    "gemini": "gemini-2.5-flash",
    "anthropic": "claude-opus-4-20250514",
    "openai": "gpt-4o",
}
N_FRAMES = 8


def configure(provider: str, model: str | None = None) -> None:
    global PROVIDER, MODEL
    PROVIDER = provider
    MODEL = model or DEFAULT_MODEL.get(provider, model)
TIER_TEXT = {"tier0_cross": "tier0_cross", "tier1_vatex_short": "tier1_vatex_short",
             "tier3_va11y": "tier3_va11y"}
LADDER = ["tier0_cross", "tier1_vatex_short", "tierM_machine_ad", "tier3_va11y"]
LADDER_GT = {t: i for i, t in enumerate(LADDER)}


def load_env():
    for l in (ROOT / ".env").read_text().splitlines():
        for k in ("GEMINI_API_KEY", "ANTHROPIC_API_KEY", "OPENAI_API_KEY"):
            if l.startswith(k):
                os.environ[k] = l.split("=", 1)[1].strip().strip('"').strip("'")


def client():
    if PROVIDER == "gemini":
        from google import genai
        return genai.Client(api_key=os.environ["GEMINI_API_KEY"])
    if PROVIDER == "anthropic":
        from anthropic import Anthropic
        return Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    if PROVIDER == "openai":
        from openai import OpenAI
        return OpenAI(api_key=os.environ["OPENAI_API_KEY"])
    raise ValueError(f"unknown provider {PROVIDER}")


def _pil_b64(img) -> str:
    import base64
    from io import BytesIO
    buf = BytesIO()
    img.convert("RGB").save(buf, format="JPEG", quality=85)
    return base64.b64encode(buf.getvalue()).decode("ascii")


def parse_json(text: str | None) -> dict:
    if not text:
        return {}
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        m = re.search(r"\{.*\}", text, flags=re.DOTALL)
        try:
            return json.loads(m.group(0)) if m else {}
        except json.JSONDecodeError:
            return {}


def _split_contents(contents):
    """Normalize contents to (prompt_text, [PIL images]).

    Accepts either a plain string (text only) or a list [text, *PIL images].
    """
    if isinstance(contents, str):
        return contents, []
    text = next((c for c in contents if isinstance(c, str)), "")
    imgs = [c for c in contents if not isinstance(c, str)]
    return text, imgs


def gen_content(cl, contents) -> str | None:
    """Provider-agnostic JSON generation. Returns text or None, with one retry."""
    text, imgs = _split_contents(contents)
    for _ in range(2):
        try:
            if PROVIDER == "gemini":
                from google.genai import types
                cfg = types.GenerateContentConfig(response_mime_type="application/json", temperature=0)
                r = cl.models.generate_content(model=MODEL, contents=contents, config=cfg)
                if r.text:
                    return r.text
            elif PROVIDER == "anthropic":
                blocks = [{"type": "image", "source": {"type": "base64",
                          "media_type": "image/jpeg", "data": _pil_b64(im)}} for im in imgs]
                blocks.append({"type": "text", "text": text + "\n\nReturn JSON only."})
                resp = cl.messages.create(model=MODEL, max_tokens=2500, temperature=0,
                                          messages=[{"role": "user", "content": blocks}])
                out = "".join(b.text for b in resp.content if getattr(b, "type", "") == "text")
                if out:
                    return out
            elif PROVIDER == "openai":
                content = [{"type": "text", "text": text}]
                for im in imgs:
                    content.append({"type": "image_url",
                                    "image_url": {"url": f"data:image/jpeg;base64,{_pil_b64(im)}"}})
                kwargs = dict(model=MODEL, temperature=0, max_tokens=2500,
                              messages=[{"role": "user", "content": content}])
                if not imgs:  # json mode is safe for text-only; some vision models reject it
                    kwargs["response_format"] = {"type": "json_object"}
                resp = cl.chat.completions.create(**kwargs)
                out = resp.choices[0].message.content
                if out:
                    return out
        except Exception:
            pass
    return None


def stable_hash(p) -> str:
    return hashlib.sha256(json.dumps(p, sort_keys=True, default=str).encode()).hexdigest()[:16]


def cache_json(name, payload, fn, refresh=False):
    CACHE.mkdir(parents=True, exist_ok=True)
    p = CACHE / f"{name}_{stable_hash(payload)}.json"
    if p.exists() and not refresh:
        return json.loads(p.read_text(encoding="utf-8"))
    r = fn()
    if r:  # do not cache empty/failed responses
        p.write_text(json.dumps(r, indent=2, ensure_ascii=False), encoding="utf-8")
    return r


def frame_paths(vid):
    return sorted((FRAMES_ROOT / vid).glob("frame_*.jpg"))[:N_FRAMES]


AD_PROMPT = """You are an automated audio-description system for blind and low-vision viewers.
Look only at the attached video frames from a ~10 second clip. Write a single audio
description of 35-55 words covering the main subject, their key action, the setting,
and important objects. Be factual and concrete; describe only what is visible. Do not
address the viewer or mention frames/video. Return JSON only: {"ad": "your description"}"""


def gen_machine_ad(cl, vid, imgs, refresh):
    payload = {"kind": "machine_ad_gemini_v1", "model": MODEL, "video_id": vid}

    def call():
        return parse_json(gen_content(cl, [AD_PROMPT, *imgs]))

    return str(cache_json("ad", payload, call, refresh).get("ad", "")).strip()


def grade_prompt(questions, candidates):
    return f"""Grade candidate audio descriptions using ADQA-style questions.
For each candidate and question, decide if the description lets a blind listener answer.
Scoring: 1.0 = directly states/inferable; 0.5 = gestures but uncertain; 0.0 = absent/contradicts.
Grade each candidate independently; candidates are unlabeled; do not guess identity or target a distribution.
Return JSON only.

Questions:
{json.dumps(questions, indent=2)}

Candidates (unlabeled):
{json.dumps(candidates, indent=2)}

Schema: {{"grades":[{{"candidate_id":"A","q_idx":0,"score":1.0}}]}}"""


def grade_all_tiers(cl, vid, questions, cand_text, seed, refresh):
    qs = [{"q_idx": int(q["q_idx"]), "question": q["question"], "answer_key": q["answer_key"]}
          for q in questions]
    tiers = list(cand_text.keys())
    rng = random.Random(seed + int(hashlib.md5(vid.encode()).hexdigest(), 16) % 9999)
    rng.shuffle(tiers)
    ids = ["A", "B", "C", "D"][: len(tiers)]
    id_to_tier = dict(zip(ids, tiers))
    cands = [{"candidate_id": cid, "description": cand_text[id_to_tier[cid]]} for cid in ids]
    payload = {"kind": "grade_all_gemini_v1", "model": MODEL, "video_id": vid,
               "questions": qs, "cands": cands, "map": id_to_tier}

    def call():
        return parse_json(gen_content(cl, grade_prompt(qs, cands)))

    parsed = cache_json("grade_all", payload, call, refresh)
    grades = parsed.get("grades", []) if isinstance(parsed, dict) else (parsed if isinstance(parsed, list) else [])
    by_tier = {t: [] for t in tiers}
    for g in grades:
        if not isinstance(g, dict):
            continue
        cid = str(g.get("candidate_id", "")).strip()
        if cid in id_to_tier:
            by_tier[id_to_tier[cid]].append(min(1.0, max(0.0, float(g.get("score", 0) or 0))))
    return {t: (float(np.mean(v)) if v else 0.0) for t, v in by_tier.items()}


def clip_top3(model, preprocess, tokenizer, device, paths, text):
    import torch
    imgs = torch.stack([preprocess(Image.open(p).convert("RGB")) for p in paths]).to(device)
    tok = tokenizer([text]).to(device)
    with torch.no_grad():
        i = model.encode_image(imgs); i = i / i.norm(dim=-1, keepdim=True)
        t = model.encode_text(tok); t = t / t.norm(dim=-1, keepdim=True)
        sims = (i @ t.T).squeeze().cpu().numpy()
    return float(np.sort(sims)[-min(3, len(sims)):].mean())


def minmax(s):
    lo, hi = s.min(), s.max()
    if not np.isfinite(lo) or hi == lo:
        return pd.Series(np.full(len(s), 0.5), index=s.index)
    return (s - lo) / (hi - lo)


def main():
    load_env()
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--seed", type=int, default=17)
    ap.add_argument("--provider", choices=["gemini", "anthropic", "openai"], default="gemini")
    ap.add_argument("--model", default=None, help="override model id (e.g. claude-opus-4-20250514, gpt-4o)")
    ap.add_argument("--refresh-cache", action="store_true")
    args = ap.parse_args()
    configure(args.provider, args.model)
    print(f"Grader: {PROVIDER} / {MODEL}")

    reg = {json.loads(l)["video_id"]: json.loads(l)
           for l in REGISTRY.read_text().splitlines() if l.strip()}
    qdf = pd.read_csv(QUESTIONS_CSV)
    clip_df = pd.read_csv(CLIP_CSV)
    clip_lookup = clip_df.set_index(["video_id", "tier"])["clip_top3"].to_dict()
    vids = [v for v in qdf["video_id"].unique() if v in reg]
    if args.limit:
        vids = vids[: args.limit]

    cl = client()
    import open_clip
    import torch
    device = "mps" if torch.backends.mps.is_available() else "cpu"
    print(f"Loading CLIP on {device} ...")
    model, _, preprocess = open_clip.create_model_and_transforms("ViT-L-14", pretrained="laion2b_s32b_b82k")
    tokenizer = open_clip.get_tokenizer("ViT-L-14")
    model.to(device).eval()

    rows = []
    for i, vid in enumerate(vids):
        paths = frame_paths(vid)
        if len(paths) < N_FRAMES:
            print(f"[{i+1}/{len(vids)}] {vid}: skip frames"); continue
        meta = reg[vid]
        imgs = [Image.open(p).convert("RGB") for p in paths]
        questions = qdf[qdf.video_id == vid].to_dict("records")

        machine_ad = gen_machine_ad(cl, vid, imgs, args.refresh_cache)
        if len(machine_ad.split()) < 8:
            print(f"[{i+1}/{len(vids)}] {vid}: skip (AD gen failed)"); continue
        cand_text = {
            "tier0_cross": meta["tier0_cross"],
            "tier1_vatex_short": meta["tier1_vatex_short"],
            "tierM_machine_ad": machine_ad,
            "tier3_va11y": meta["tier3_va11y"],
        }
        adqa = grade_all_tiers(cl, vid, questions, cand_text, args.seed, args.refresh_cache)
        clipM = clip_top3(model, preprocess, tokenizer, device, paths, machine_ad)
        for tier in LADDER:
            ct = clipM if tier == "tierM_machine_ad" else clip_lookup.get((vid, tier), np.nan)
            rows.append({"video_id": vid, "tier": tier, "gt": LADDER_GT[tier],
                         "adqa_score": adqa.get(tier, 0.0), "clip_top3": ct,
                         "text": cand_text[tier] if tier == "tierM_machine_ad" else ""})
        print(f"[{i+1}/{len(vids)}] {vid}: M_adqa={adqa.get('tierM_machine_ad',0):.2f} "
              f"M_clip={clipM:.3f} pro_adqa={adqa.get('tier3_va11y',0):.2f} | {machine_ad[:50]}...")

    full = pd.DataFrame(rows).dropna(subset=["clip_top3"])
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    full.to_csv(OUT_CSV, index=False)

    full["adqa_norm"] = full.groupby("video_id", group_keys=False)["adqa_score"].apply(minmax)
    full["clip_norm"] = full.groupby("video_id", group_keys=False)["clip_top3"].apply(minmax)
    full["ensemble"] = 0.5 * full["adqa_norm"] + 0.5 * full["clip_norm"]

    def metrics(col):
        rho = float(spearmanr(full["gt"], full[col])[0])
        fo = tot = 0
        for _, g in full.groupby("video_id"):
            by = dict(zip(g["tier"], g[col]))
            if all(t in by for t in LADDER):
                tot += 1
                fo += int(by["tier0_cross"] < by["tier1_vatex_short"] < by["tierM_machine_ad"] < by["tier3_va11y"])
        return {"rho": rho, "full_order": fo, "n": tot, "rate": fo / tot if tot else float("nan")}

    piv = full.pivot_table(index="video_id", columns="tier", values="ensemble")
    sanity = {
        "machine>crowd": float((piv["tierM_machine_ad"] > piv["tier1_vatex_short"]).mean()),
        "expert>machine": float((piv["tier3_va11y"] > piv["tierM_machine_ad"]).mean()),
        "machine>cross": float((piv["tierM_machine_ad"] > piv["tier0_cross"]).mean()),
    }
    report = {
        "run_at": datetime.now(timezone.utc).isoformat(),
        "grader": MODEL, "n_clips": int(full.video_id.nunique()),
        "ladder": "cross < crowd_short < machine_AD < expert_AD",
        "ensemble": metrics("ensemble"), "adqa_only": metrics("adqa_score"),
        "clip_only": metrics("clip_top3"), "rung_sanity": sanity,
    }
    OUT_JSON.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print("\n=== 4-TIER w/ MACHINE-AD RUNG (Gemini grader) ===")
    print("ensemble:", json.dumps(report["ensemble"]))
    print("rung sanity:", json.dumps(sanity))
    print(f"Wrote {OUT_JSON}")


if __name__ == "__main__":
    main()
