#!/usr/bin/env python3
"""Research analysis: split TRIBE need into slotable vs collision debt.

First-principles framing:
- Visual need is not enough. AD can only help when there is either silence to
  speak into or a willingness to alter the original audio experience.
- A high TRIBE AV-A gap during silence is "slotable debt": standard AD can be
  inserted.
- A high TRIBE AV-A gap during speech is "collision debt": standard AD will
  collide with dialogue/narration, so the clip needs extended, integrated, or
  interactive description.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
NEED_WINDOWS = ROOT / "output" / "scenetwin_timing_20clip" / "need" / "coarse_need_windows.csv"
FORECAST = ROOT / "output" / "scenetwin_timing_20clip" / "tribe_native" / "tribe_failure_forecast.csv"
OUT_DIR = ROOT / "cursor" / "output"
OUT_CSV = OUT_DIR / "neural_accessibility_debt.csv"
OUT_REPORT = ROOT / "cursor" / "findings" / "neural-accessibility-debt.md"


def rank_corr(a: pd.Series, b: pd.Series) -> float:
    data = pd.DataFrame({"a": a, "b": b}).dropna()
    if len(data) < 2:
        return float("nan")
    return float(data["a"].rank().corr(data["b"].rank()))


def markdown_table(df: pd.DataFrame, columns: list[str]) -> str:
    rows = ["| " + " | ".join(columns) + " |", "| " + " | ".join(["---"] * len(columns)) + " |"]
    for record in df[columns].to_dict(orient="records"):
        values = []
        for col in columns:
            value = record[col]
            if isinstance(value, float):
                if pd.isna(value):
                    values.append("unlabeled")
                else:
                    values.append(f"{value:.3f}")
            elif pd.isna(value):
                values.append("unlabeled")
            else:
                values.append(str(value))
        rows.append("| " + " | ".join(values) + " |")
    return "\n".join(rows)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_REPORT.parent.mkdir(parents=True, exist_ok=True)

    windows = pd.read_csv(NEED_WINDOWS)
    forecast = pd.read_csv(FORECAST)

    w = windows.copy()
    w["duration"] = w["end_s"] - w["start_s"]
    w["weighted_need"] = w["need_score"] * w["duration"]
    w["slotable_debt"] = w["need_score"] * (1.0 - w["speech_density"]) * w["duration"]
    w["collision_debt"] = w["need_score"] * w["speech_density"] * w["duration"]
    w["high_need"] = w["need_score"] >= 0.5

    grouped = w.groupby("clip_idx").agg(
        duration_s=("duration", "sum"),
        mean_need=("need_score", "mean"),
        total_need=("weighted_need", "sum"),
        slotable_debt=("slotable_debt", "sum"),
        collision_debt=("collision_debt", "sum"),
        high_need_windows=("high_need", "sum"),
        mean_speech_density=("speech_density", "mean"),
    )
    grouped["slotable_debt_frac"] = grouped["slotable_debt"] / grouped["total_need"].replace(0, pd.NA)
    grouped["collision_debt_frac"] = grouped["collision_debt"] / grouped["total_need"].replace(0, pd.NA)
    grouped["debt_mode"] = "balanced"
    grouped.loc[grouped["collision_debt_frac"] >= 0.65, "debt_mode"] = "collision"
    grouped.loc[grouped["slotable_debt_frac"] >= 0.65, "debt_mode"] = "slotable"

    cols = [
        "clip_idx",
        "category",
        "risk_rank",
        "risk_score",
        "target",
        "quality_risk",
        "tribe_route",
        "all4_mean_full_order",
        "all4_mean_tier3_margin",
    ]
    merged = grouped.reset_index().merge(forecast[cols], on="clip_idx", how="left")
    merged = merged.sort_values(["risk_rank", "clip_idx"])
    labeled = merged[merged["all4_mean_full_order"].notna()].copy()
    merged.to_csv(OUT_CSV, index=False)

    mode_counts = merged["debt_mode"].value_counts().to_dict()
    top_collision = merged.sort_values("collision_debt", ascending=False).head(6)
    top_slotable = merged.sort_values("slotable_debt", ascending=False).head(6)
    correlations = {
        "collision_debt_vs_full_order": rank_corr(labeled["collision_debt"], labeled["all4_mean_full_order"]),
        "slotable_debt_vs_full_order": rank_corr(labeled["slotable_debt"], labeled["all4_mean_full_order"]),
        "collision_frac_vs_tier3_margin": rank_corr(labeled["collision_debt_frac"], labeled["all4_mean_tier3_margin"]),
        "slotable_frac_vs_tier3_margin": rank_corr(labeled["slotable_debt_frac"], labeled["all4_mean_tier3_margin"]),
    }

    collision_cols = ["clip_idx", "category", "collision_debt", "collision_debt_frac", "risk_rank", "quality_risk", "tribe_route"]
    slotable_cols = ["clip_idx", "category", "slotable_debt", "slotable_debt_frac", "risk_rank", "quality_risk", "tribe_route"]

    report = f"""# Neural Accessibility Debt

Generated by `cursor/neural_accessibility_debt.py`.

## First-principles claim

TRIBE should not be treated as another caption-quality score. Its stronger use is
to expose **visual information debt** before evaluating any candidate audio
description:

- **Slotable debt** = visual need during silence or low speech density.
- **Collision debt** = visual need while speech/audio is already occupied.

These are different product/research problems. Slotable debt can be solved with
standard AD insertion. Collision debt needs extended AD, integrated AD, pauseable
playback, or user-queryable description.

## Current evidence

- Need-window clips analyzed: **{len(merged)}**
- Clips with cached evaluator/failure labels: **{len(labeled)}**
- Debt modes: `{mode_counts}`
- Known all-judge failures caught by top-2 existing TRIBE risk rank: **{int((merged.sort_values('risk_rank').head(2)['target'] == 1).sum())}/2**

Rank correlations on the 18 cached clips:

| Signal | Spearman rho |
|---|---:|
| collision_debt vs full tier order | {correlations['collision_debt_vs_full_order']:.3f} |
| slotable_debt vs full tier order | {correlations['slotable_debt_vs_full_order']:.3f} |
| collision_debt_frac vs tier3 margin | {correlations['collision_frac_vs_tier3_margin']:.3f} |
| slotable_debt_frac vs tier3 margin | {correlations['slotable_frac_vs_tier3_margin']:.3f} |

## Highest collision debt clips

{markdown_table(top_collision, collision_cols)}

## Highest slotable debt clips

{markdown_table(top_slotable, slotable_cols)}

## Research implication

The next SceneTwin research question should be:

> Can we forecast *the required accessibility intervention*, not merely score
> an AD transcript?

That reframes TRIBE from an evaluator into a **policy layer**:

1. low debt: no AD or lightweight summary,
2. slotable debt: standard inserted AD,
3. collision debt: extended/integrated/interactive AD,
4. high debt plus low evaluator margin: mandatory human review.

This is more native to TRIBE because it uses modality counterfactuals
(`P_AV - P_A`) and speech occupancy, not text-quality imitation.
"""
    OUT_REPORT.write_text(report, encoding="utf-8")

    print(f"Wrote {OUT_CSV}")
    print(f"Wrote {OUT_REPORT}")
    print("\nDebt modes:")
    print(merged["debt_mode"].value_counts().to_string())
    print("\nCorrelations:")
    for name, value in correlations.items():
        print(f"{name}: {value:.3f}")


if __name__ == "__main__":
    main()
